version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/student-portal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: aditya
    networks:
      - student-net

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - student-net


  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aditya
      POSTGRES_DB: student-portal
    ports:
      - "5432:5432"
    networks:
      - student-net
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  student-net:

volumes:
  pgdata:
